### ISSUE TITLE
New Wrike API Integration User

### ISSUE THREAD

**Issue by Historfic** [heynicejacket/wrike-api-101#5]
Hello friend, it is my first time using Wrike ask by my client. Is there any advice you can give me?

**Comment by Historfic** [comment]
Ohh hello sir! Thank you for your response and I am sorry for the late
reply busy working on the gsheet api.
My client wants to upload the data to Wrike automatically. Currently, I
don't have any idea for now how can I transfer data to Wrike from
googlesheet. Do ypu have any advice for this area?

**Comment by heynicejacket** [comment]
I can't speak to your specific requirements, but I would probably take what I needed from Google Sheets, put it into a DataFrame, and then use one of the create functions.

For instance, if each row in Google Sheets is a task, and need to create tasks, use `wrike.task.create_task()` - this would create a single task, so you might need to loop through the DataFrame.

If you had to update an existing task, you'd need a way to map Google Sheets rows to Wrike task (last time I looked, Google Sheets doesn't have a back end row ID), and then use `update_task()`.

Same for projects, folders, etc. Does that help?

**Comment by Historfic** [comment]
Yes, it makes sense. Thanks for the advice!
